## Docker Compose for local developement
## Deploys FastAPI and Postgres DB

name: williams-eng-acc
services:
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-williams}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  api:
    build:
      context: ..
      dockerfile: api/docker/Dockerfile
      target: development
    env_file:
      - .env
    volumes:
      - ../api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  etl:
    build:
      context: ..
      dockerfile: etl/docker/Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ../data:/app/data
    command: ["python", "duckdb_pipeline.py"]

volumes:
  postgres_data: